version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: shopping_list_db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: shopping_list_api
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '3333:3333'
    env_file:
      - .env
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

volumes:
  pgdata:
  grafana-data:
  prometheus_data:
