version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: todo_list_postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: duds
      POSTGRES_PASSWORD: duds123
      POSTGRES_DB: todo_list_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
